In [92]:
import pandas as pd
from joblib import load
import numpy as np

from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, matthews_corrcoef, confusion_matrix

In [93]:
scaler_instance = load("../../results/rmssd/sta_scaler.joblib")
svm_model = load("../../results/rmssd/svm_model.joblib")
lr_model = load("../../results/rmssd/lr_model.joblib")
rf_model = load("../../results/rmssd/rf_model.joblib")
knn_model = load("../../results/rmssd/knn_model.joblib")
dt_model = load("../../results/rmssd/dt_model.joblib")
ab_model = load("../../results/rmssd/ab_model.joblib")

In [94]:
val_data = pd.read_csv("../../process_dataset/rmssd/val_data.csv")
test_data = pd.read_csv("../../process_dataset/rmssd/test_data.csv")

y_val = np.load("../../process_dataset/rmssd/y_val.npy", allow_pickle=True)
y_test = np.load("../../process_dataset/rmssd/y_test.npy", allow_pickle=True)

In [95]:
val_data_scaler = scaler_instance.transform(val_data.values)
test_data_scaler = scaler_instance.transform(test_data.values)

In [96]:
predict_val_svm = svm_model.predict(X=val_data_scaler)
predict_test_svm = svm_model.predict(X=test_data_scaler)

c:\Users\hantr\anaconda3\envs\ML_Class\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
c:\Users\hantr\anaconda3\envs\ML_Class\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [97]:
predict_val_lr = lr_model.predict(X=val_data_scaler)
predict_test_lr = lr_model.predict(X=test_data_scaler)

c:\Users\hantr\anaconda3\envs\ML_Class\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
c:\Users\hantr\anaconda3\envs\ML_Class\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [98]:
predict_val_rf = rf_model.predict(X=val_data_scaler)
predict_test_rf = rf_model.predict(X=test_data_scaler)

c:\Users\hantr\anaconda3\envs\ML_Class\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Users\hantr\anaconda3\envs\ML_Class\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [99]:
predict_val_knn = knn_model.predict(X=val_data_scaler)
predict_test_knn = knn_model.predict(X=test_data_scaler)

c:\Users\hantr\anaconda3\envs\ML_Class\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
c:\Users\hantr\anaconda3\envs\ML_Class\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [100]:
predict_val_dt = dt_model.predict(X=val_data_scaler)
predict_test_dt = dt_model.predict(X=test_data_scaler)

c:\Users\hantr\anaconda3\envs\ML_Class\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\hantr\anaconda3\envs\ML_Class\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [101]:
predict_val_ab = ab_model.predict(X=val_data_scaler)
predict_test_ab = ab_model.predict(X=test_data_scaler)

c:\Users\hantr\anaconda3\envs\ML_Class\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
c:\Users\hantr\anaconda3\envs\ML_Class\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(


In [102]:
list(set(y_val))

['Normal', 'Abnormal', 'Inconclusive']

In [103]:
acc_value = accuracy_score(y_pred=predict_val_svm, y_true=y_val) 
recall_value = recall_score(y_pred=predict_val_svm, y_true=y_val, average='weighted')
precision_value = precision_score(y_pred=predict_val_svm, y_true=y_val, average='weighted') 
f1_value = f1_score(y_pred=predict_val_svm, y_true=y_val, average='weighted')
mcc_value = matthews_corrcoef(y_pred=predict_val_svm, y_true=y_val)
cm = confusion_matrix(y_pred=predict_val_svm, y_true=y_val)

[acc_value, recall_value, precision_value, f1_value, mcc_value, cm]

[0.32852852852852854,
 0.32852852852852854,
 0.32853490360163334,
 0.328498636173384,
 -0.007338477736802948,
 array([[1137, 1100, 1132],
        [1144, 1067, 1085],
        [1181, 1066, 1078]], dtype=int64)]

In [104]:
acc_value = accuracy_score(y_pred=predict_val_lr, y_true=y_val) 
recall_value = recall_score(y_pred=predict_val_lr, y_true=y_val, average='weighted')
precision_value = precision_score(y_pred=predict_val_lr, y_true=y_val, average='weighted') 
f1_value = f1_score(y_pred=predict_val_lr, y_true=y_val, average='weighted')
mcc_value = matthews_corrcoef(y_pred=predict_val_lr, y_true=y_val)
cm = confusion_matrix(y_pred=predict_val_lr, y_true=y_val)

[acc_value, recall_value, precision_value, f1_value, mcc_value, cm]

[0.3337337337337337,
 0.3337337337337337,
 0.3334128063512958,
 0.3293944836290401,
 -0.0004476863588186351,
 array([[1425,  817, 1127],
        [1456,  787, 1053],
        [1410,  793, 1122]], dtype=int64)]

In [105]:
acc_value = accuracy_score(y_pred=predict_test_rf, y_true=y_test) 
recall_value = recall_score(y_pred=predict_test_rf, y_true=y_test, average='weighted')
precision_value = precision_score(y_pred=predict_test_rf, y_true=y_test, average='weighted') 
f1_value = f1_score(y_pred=predict_test_rf, y_true=y_test, average='weighted')
mcc_value = matthews_corrcoef(y_pred=predict_test_rf, y_true=y_test)
cm = confusion_matrix(y_pred=predict_test_rf, y_true=y_test)

[acc_value, recall_value, precision_value, f1_value, mcc_value, cm]

[0.35477477477477476,
 0.35477477477477476,
 0.3548881900188515,
 0.35481339749708535,
 0.032186255993715225,
 array([[656, 592, 597],
        [634, 643, 562],
        [575, 621, 670]], dtype=int64)]

In [106]:
acc_value = accuracy_score(y_pred=predict_test_knn, y_true=y_test) 
recall_value = recall_score(y_pred=predict_test_knn, y_true=y_test, average='weighted')
precision_value = precision_score(y_pred=predict_test_knn, y_true=y_test, average='weighted') 
f1_value = f1_score(y_pred=predict_test_knn, y_true=y_test, average='weighted')
mcc_value = matthews_corrcoef(y_pred=predict_test_knn, y_true=y_test)
cm = confusion_matrix(y_pred=predict_test_knn, y_true=y_test)

[acc_value, recall_value, precision_value, f1_value, mcc_value, cm]

[0.3630630630630631,
 0.3630630630630631,
 0.36753367966231343,
 0.3573589505114326,
 0.04617448766495053,
 array([[879, 582, 384],
        [820, 662, 357],
        [798, 594, 474]], dtype=int64)]

In [107]:
acc_value = accuracy_score(y_pred=predict_test_dt, y_true=y_test) 
recall_value = recall_score(y_pred=predict_test_dt, y_true=y_test, average='weighted')
precision_value = precision_score(y_pred=predict_test_dt, y_true=y_test, average='weighted') 
f1_value = f1_score(y_pred=predict_test_dt, y_true=y_test, average='weighted')
mcc_value = matthews_corrcoef(y_pred=predict_test_dt, y_true=y_test)
cm = confusion_matrix(y_pred=predict_test_dt, y_true=y_test)

[acc_value, recall_value, precision_value, f1_value, mcc_value, cm]

[0.3472072072072072,
 0.3472072072072072,
 0.34771929423704345,
 0.34693389363589,
 0.021005897226804682,
 array([[688, 589, 568],
        [686, 637, 516],
        [643, 621, 602]], dtype=int64)]

In [108]:
acc_value = accuracy_score(y_pred=predict_test_ab, y_true=y_test) 
recall_value = recall_score(y_pred=predict_test_ab, y_true=y_test, average='weighted')
precision_value = precision_score(y_pred=predict_test_ab, y_true=y_test, average='weighted') 
f1_value = f1_score(y_pred=predict_test_ab, y_true=y_test, average='weighted')
mcc_value = matthews_corrcoef(y_pred=predict_test_ab, y_true=y_test)
cm = confusion_matrix(y_pred=predict_test_ab, y_true=y_test)

[acc_value, recall_value, precision_value, f1_value, mcc_value, cm]

[0.32432432432432434,
 0.32432432432432434,
 0.32343334822629866,
 0.3175628593868209,
 -0.013906486537744598,
 array([[810, 456, 579],
        [851, 386, 602],
        [861, 401, 604]], dtype=int64)]

In [109]:
rf_model.predict_proba(X=test_data_scaler)

c:\Users\hantr\anaconda3\envs\ML_Class\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([[0.09666667, 0.57      , 0.33333333],
       [0.11716667, 0.80283333, 0.08      ],
       [0.24      , 0.05      , 0.71      ],
       ...,
       [0.162     , 0.48616667, 0.35183333],
       [0.01      , 0.03      , 0.96      ],
       [0.64      , 0.09      , 0.27      ]])