In [55]:
import pandas as pd
from joblib import load
import numpy as np

from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, matthews_corrcoef, confusion_matrix

In [56]:
model_list=[]
scaler_list_val=[]
scaler_list_test=[]

In [57]:
scaler_instance_sta = load("../results/sta_scaler.joblib")
scaler_instance_rob = load("../results/rob_scaler.joblib")
scaler_instance_mm = load("../results/mm_scaler.joblib")
model_list.append(('Support Vector Machine', load("../results/svm_model.joblib")))
model_list.append(('Logistic Regression', load("../results/lr_model.joblib")))
model_list.append(('Random Forest', load("../results/rf_model.joblib")))
model_list.append(('K-Nearest Neighbors', load("../results/knn_model.joblib")))
model_list.append(('Decision Tree', load("../results/dt_model.joblib")))
model_list.append(('AdaBoost', load("../results/ab_model.joblib")))

In [58]:
#Se cargan los datos de validación y test
val_data = pd.read_csv("../process_dataset/val_data.csv")
test_data = pd.read_csv("../process_dataset/test_data.csv")

y_val = np.load("../process_dataset/y_val.npy", allow_pickle=True)
y_test = np.load("../process_dataset/y_test.npy", allow_pickle=True)

In [59]:
#Se escalan los datos de validación y test
scaler_list_val.append(('Standard Scaler Val', scaler_instance_sta.transform(val_data.values)))
scaler_list_test.append(('Standard Scaler Test', scaler_instance_sta.transform(test_data.values)))
scaler_list_val.append(('Robust Scaler Val', scaler_instance_rob.transform(val_data.values)))
scaler_list_test.append(('Robust Scaler Test', scaler_instance_rob.transform(test_data.values)))
scaler_list_val.append(('Min-Max Scaler Val', scaler_instance_mm.transform(val_data.values)))
scaler_list_test.append(('Min-Max Scaler Test', scaler_instance_mm.transform(test_data.values)))

In [60]:
for i in model_list:
    for j in scaler_list_val:
        predict_val = i.predict(X=j)
        print("Accuracy: ", accuracy_score(predict_val, y_val))
        print("Recall: ", recall_score(predict_val, y_val, average='weighted'))
        print("Precision: ", precision_score(predict_val, y_val, average='weighted'))
        print("F1: ", f1_score(predict_val, y_val, average='weighted'))
        print("MCC: ", matthews_corrcoef(predict_val, y_val))
        print("Confusion Matrix: \n", confusion_matrix(predict_val, y_val))
        print("\n")

/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


Accuracy:  0.32852852852852854
Recall:  0.32852852852852854
Precision:  0.3286551980143241
F1:  0.32855842088367304
MCC:  -0.007338477736802948
Confusion Matrix: 
 [[1137 1144 1181]
 [1100 1067 1066]
 [1132 1085 1078]]




/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


Accuracy:  0.32982982982982983
Recall:  0.32982982982982983
Precision:  0.4333013617467824
F1:  0.36521944171000115
MCC:  -0.006360975833206958
Confusion Matrix: 
 [[1641 1648 1616]
 [1493 1420 1475]
 [ 235  228  234]]




/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


Accuracy:  0.3316316316316316
Recall:  0.3316316316316316
Precision:  0.4660097521760196
F1:  0.36973712828336763
MCC:  -0.004965947427525461
Confusion Matrix: 
 [[2026 2024 1984]
 [1056 1009 1063]
 [ 287  263  278]]


Accuracy:  0.3337337337337337
Recall:  0.3337337337337337
Precision:  0.3505067985150279
F1:  0.3380729838384273
MCC:  -0.0004476863588186351
Confusion Matrix: 
 [[1425 1456 1410]
 [ 817  787  793]
 [1127 1053 1122]]




/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


Accuracy:  0.33263263263263265
Recall:  0.33263263263263265
Precision:  0.4298868850261765
F1:  0.35451641967193853
MCC:  -0.003560630571366002
Confusion Matrix: 
 [[1968 1967 1986]
 [ 733  716  700]
 [ 668  613  639]]


Accuracy:  0.3395395395395395
Recall:  0.3395395395395395
Precision:  0.5722886953330966


/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


F1:  0.39278541585863846
MCC:  0.007068023101565792
Confusion Matrix: 
 [[2459 2401 2409]
 [ 317  340  323]
 [ 593  555  593]]


Accuracy:  0.35535535535535534
Recall:  0.35535535535535534
Precision:  0.35559546312811
F1:  0.3554440460013501
MCC:  0.03291757397630367
Confusion Matrix: 
 [[1243 1131 1064]
 [1029 1115 1069]
 [1097 1050 1192]]




/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


Accuracy:  0.33633633633633636
Recall:  0.33633633633633636
Precision:  0.33724767346896545
F1:  0.3366001591674406
MCC:  0.004574278045868546
Confusion Matrix: 
 [[1157 1064 1121]
 [1148 1177 1178]
 [1064 1055 1026]]


Accuracy:  0.3278278278278278
Recall:  0.3278278278278278
Precision:  0.3288370696789711
F1:  0.32806893601610715
MCC:  -0.008401286526589209
Confusion Matrix: 
 [[1186 1202 1170]
 [1156 1072 1138]
 [1027 1022 1017]]




/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


Accuracy:  0.35305305305305307
Recall:  0.35305305305305307
Precision:  0.3818257671254486
F1:  0.360250843229022
MCC:  0.02934679539248824
Confusion Matrix: 
 [[1609 1472 1502]
 [1032 1141 1046]
 [ 728  683  777]]




/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


Accuracy:  0.34074074074074073
Recall:  0.34074074074074073
Precision:  0.3696655774551049
F1:  0.3481497922313085
MCC:  0.010556024575402083
Confusion Matrix: 
 [[1550 1490 1503]
 [1129 1125 1093]
 [ 690  681  729]]




/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


Accuracy:  0.325025025025025
Recall:  0.325025025025025
Precision:  0.359023792631258
F1:  0.334868545948836
MCC:  -0.013591970015268785
Confusion Matrix: 
 [[1537 1502 1533]
 [1134 1091 1173]
 [ 698  703  619]]


Accuracy:  0.342042042042042
Recall:  0.342042042042042
Precision:  0.3458155663340782
F1:  0.34302468167624006
MCC:  0.012727876635213487
Confusion Matrix: 
 [[1331 1265 1222]
 [1080 1059 1076]
 [ 958  972 1027]]


Accuracy:  0.3342342342342342
Recall:  0.3342342342342342


/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


Precision:  0.3387954815988059
F1:  0.3355186432075175
MCC:  0.0009879986724568774
Confusion Matrix: 
 [[1313 1240 1280]
 [1097 1068 1087]
 [ 959  988  958]]


Accuracy:  0.33993993993993993
Recall:  0.33993993993993993
Precision:  0.34341711286341337
F1:  0.3407730226994818
MCC:  0.009631259562236262
Confusion Matrix: 
 [[1279 1275 1230]
 [1081 1127 1105]
 [1009  894  990]]


Accuracy:  0.33633633633633636
Recall:  0.33633633633633636
Precision:  0.3594343773692562


/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(


F1:  0.3423643562867451
MCC:  0.003358590244318516
Confusion Matrix: 
 [[1494 1483 1463]
 [ 758  745  741]
 [1117 1068 1121]]


Accuracy:  0.33563563563563564
Recall:  0.33563563563563564
Precision:  0.45297045402488295
F1:  0.36271703874935907
MCC:  0.000928403900165239
Confusion Matrix: 
 [[2062 2021 2041]
 [ 516  533  526]
 [ 791  742  758]]


Accuracy:  0.33863863863863863
Recall:  0.33863863863863863
Precision:  0.5981029860575806
F1:  0.3970378783772768
MCC:  0.005560789689737956
Confusion Matrix: 
 [[2539 2488 2479]
 [ 452  445  447]
 [ 378  363  399]]




/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(


In [61]:
for i in model_list:
    for j in scaler_list_test:
        predict_test = i.predict(X=j)
        print("Accuracy: ", accuracy_score(predict_test, y_test))
        print("Recall: ", recall_score(predict_test, y_test, average='weighted'))
        print("Precision: ", precision_score(predict_test, y_test, average='weighted'))
        print("F1: ", f1_score(predict_test, y_test, average='weighted'))
        print("MCC: ", matthews_corrcoef(predict_test, y_test))
        print("Confusion Matrix: \n", confusion_matrix(predict_test, y_test))
        print("\n")

/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


Accuracy:  0.3504504504504504
Recall:  0.3504504504504504
Precision:  0.35149578779419155
F1:  0.35075016552191063
MCC:  0.025635835951300364
Confusion Matrix: 
 [[695 616 646]
 [555 599 569]
 [595 624 651]]




/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


Accuracy:  0.34
Recall:  0.34
Precision:  0.4426434045729066
F1:  0.37403279394773414
MCC:  0.01258712131689221
Confusion Matrix: 
 [[931 893 920]
 [778 803 793]
 [136 143 153]]




/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


Accuracy:  0.3436036036036036
Recall:  0.3436036036036036
Precision:  0.48531396220589673
F1:  0.38240820697424865
MCC:  0.01880861575776078
Confusion Matrix: 
 [[1157 1102 1109]
 [ 539  580  587]
 [ 149  157  170]]


Accuracy:  0.3324324324324324
Recall:  0.3324324324324324
Precision:  0.3522614743412462
F1:  0.33756309421278313
MCC:  -0.0015523835579581817
Confusion Matrix: 
 [[789 796 814]
 [452 420 416]
 [604 623 636]]


Accuracy:  0.3335135135135135
Recall:  0.3335135135135135
Precision:  0.4426104892863688
F1:  0.35749677690964166
MCC:  0.0009628901382544883
Confusion Matrix: 
 [[1111 1124 1114]
 [ 394  371  383]
 [ 340  344  369]]


Accuracy:  0.3254054054054054
Recall:  0.3254054054054054


/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


Precision:  0.5744639067906485
F1:  0.38375935809558753
MCC:  -0.014324365102771562
Confusion Matrix: 
 [[1347 1375 1375]
 [ 190  149  181]
 [ 308  315  310]]


Accuracy:  0.35495495495495494
Recall:  0.35495495495495494
Precision:  0.35492899426836066
F1:  0.35492081619332055
MCC:  0.032459514850308895
Confusion Matrix: 
 [[661 633 575]
 [591 641 623]
 [593 565 668]]




/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


Accuracy:  0.32306306306306304
Recall:  0.32306306306306304
Precision:  0.32373384270535666
F1:  0.3230786765422159
MCC:  -0.015258090431146782
Confusion Matrix: 
 [[624 689 642]
 [653 591 646]
 [568 559 578]]


Accuracy:  0.3311711711711712
Recall:  0.3311711711711712
Precision:  0.3331104461889122
F1:  0.33168320636617904
MCC:  -0.003046083818608281
Confusion Matrix: 
 [[663 652 653]
 [629 622 660]
 [553 565 553]]




/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


Accuracy:  0.36486486486486486
Recall:  0.36486486486486486
Precision:  0.3906613270804493
F1:  0.3704650396635109
MCC:  0.04892665846838404
Confusion Matrix: 
 [[879 817 794]
 [582 669 595]
 [384 353 477]]




/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


Accuracy:  0.34540540540540543
Recall:  0.34540540540540543
Precision:  0.3814443547400433
F1:  0.35504474371472
MCC:  0.019321440809767988
Confusion Matrix: 
 [[892 831 839]
 [571 639 641]
 [382 369 386]]




/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


Accuracy:  0.3466666666666667
Recall:  0.3466666666666667
Precision:  0.3815364414938821
F1:  0.35613887247012327
MCC:  0.02129602226472202
Confusion Matrix: 
 [[883 814 808]
 [607 655 672]
 [355 370 386]]


Accuracy:  0.3466666666666667
Recall:  0.3466666666666667
Precision:  0.3484986310494133
F1:  0.3469479878388014
MCC:  0.020213853968457655
Confusion Matrix: 
 [[690 704 644]
 [585 634 622]
 [570 501 600]]


Accuracy:  0.33513513513513515
Recall:  0.33513513513513515
Precision:  0.3407868406295849
F1:  0.3362418051931974
MCC:  0.0029348828815346302
Confusion Matrix: 
 [[713 722 772]
 [569 611 558]
 [563 506 536]]


Accuracy:  0.32774774774774773
Recall:  0.32774774774774773
Precision:  0.3315843259557905
F1:  0.32864916549839235
MCC:  -0.008155001411942546
Confusion Matrix: 
 [[671 698 728]
 [608 624 614]
 [566 517 524]]


Accuracy:  0.32432432432432434
Recall:  0.32432432432432434


/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but AdaBoostC

Precision:  0.3506130521840412
F1:  0.3310857892618278
MCC:  -0.013906486537744598
Confusion Matrix: 
 [[810 851 861]
 [456 386 401]
 [579 602 604]]


Accuracy:  0.3318918918918919
Recall:  0.3318918918918919
Precision:  0.442166575534535
F1:  0.356338834269069
MCC:  -0.0020727091815002673
Confusion Matrix: 
 [[1097 1120 1144]
 [ 309  299  276]
 [ 439  420  446]]


Accuracy:  0.32684684684684684
Recall:  0.32684684684684684
Precision:  0.5963841302551472
F1:  0.388721082491876
MCC:  -0.01136143184505715
Confusion Matrix: 
 [[1389 1390 1409]
 [ 258  223  255]
 [ 198  226  202]]




/home/jmartin/miniconda3/envs/ML_Class/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
